Add condition to check if the error happens there

diff --git a/distribution/packages/src/deb/debian/prerm b/distribution/packages/src/deb/debian/prerm
--- a/distribution/packages/src/deb/debian/prerm
+++ b/distribution/packages/src/deb/debian/prerm
@@ -19,7 +19,10 @@ case "$1" in
         # Stop existing service
         if command -v systemctl >/dev/null && systemctl is-active wazuh-indexer.service >/dev/null; then
             echo "Stop existing wazuh-indexer.service"
-            systemctl --no-reload stop wazuh-indexer.service
+            if ! systemctl --no-reload stop wazuh-indexer.service; then
+                echo "Error while stopping the wazuh indexer service" >&2
+                exit 1
+    fi
         fi
         if command -v systemctl >/dev/null && systemctl is-active wazuh-indexer-performance-analyzer.service >/dev/null; then
             echo "Stop existing wazuh-indexer-performance-analyzer.service"
